[build]
  publish = "build"
  command = "npm run build"

# Redirect /mcp to the Cloudflare Worker
[[redirects]]
  from = "/mcp"
  to = "https://tech-detect-mcp.nabeel-thotti.workers.dev/"
  status = 301
  force = true

[[redirects]]
  from = "/mcp/*"
  to = "https://tech-detect-mcp.nabeel-thotti.workers.dev/:splat"
  status = 301
  force = true

# Handle client-side routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
