[build]
  publish = "build"
  command = "npm run build"

# Proxy any "/mcp" request to your Worker, but keep the Netlify URL
[[redirects]]
  from     = "/mcp"
  to       = "https://tech-detect-mcp.nabeel-thotti.workers.dev/"
  status   = 200
  force    = true
  conditions = {Path = ["/mcp"]}

[[redirects]]
  from     = "/mcp/*"
  to       = "https://tech-detect-mcp.nabeel-thotti.workers.dev/:splat"
  status   = 200
  force    = true
  conditions = {Path = ["/mcp/*"]}

# Handle client-side routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
